describe('product page tests', () => {
  it('should visits the product with id 1', () => {
    cy.visit('http://localhost:4200/category/bestsellers')
    cy.get("[data-cy='product__img']:first")
      .click()
    cy.url().should('include', '/products/1')
  })

  it('should visits the product page and send comment', () => {
    cy.visit('http://localhost:4200/products/1')
    cy.get("[data-cy='email__input']")
      .type('fake@email.com')
      .should('have.value', 'fake@email.com')
    cy.get("[data-cy='name__input']")
      .type('fakeName')
      .should('have.value', 'fakeName')
    cy.get("[data-cy='text__textarea']")
      .type('fakeText')
      .should('have.value', 'fakeText')
    cy.get("[data-cy='score__select']")
      .select('3')
      .should('have.value', '3')
    cy.get("[data-cy='submit']")
      .click()
    cy.get("[data-cy='comment']:last-child > [data-cy='comment__text']")
      .should('have.text', 'fakeText')
    cy.get("[data-cy='comment']:last-child > [data-cy='comment__score']")
      .should('include.text', '3')
    cy.get("[data-cy='comment']:last-child > [data-cy='comment__name']")
      .should('have.text', 'fakeName')
  })
})
